#!/usr/bin/env python3

import sys
import subprocess
import os.path
import platform

import kconfiglib

KERNEL_SERIES="placeholder"
ARCH=platform.machine()
KERNEL_PREV=None

CONFIG=os.path.expanduser("/config")

def collect_config(f):
    config = {}
    for line in f:
        line = line.strip()
        if line.startswith("# CONFIG_"):
            opt = line[len("# CONFIG_"):-len(" is not set")]
            value = "n"
        elif line.startswith("CONFIG_"):
            [opt, value] = line.strip().split("=")
            opt = opt[len("CONFIG_"):]
        else:
            continue

        config[opt] = value
    return config

CONFIG_FILE = os.path.join(CONFIG, "kernel_config-%s" % KERNEL_SERIES)
if ARCH != "x86_64":
    CONFIG_FILE += "-" + ARCH

PREV_FILE = os.path.join(CONFIG, "kernel_config-%s" % KERNEL_PREV)
if ARCH != "x86_64":
    CONFIG_FILE += "-" + ARCH

if KERNEL_PREV:
    with open(PREV_FILE) as f:
        prev = collect_config(f)

with open(CONFIG_FILE) as f:
    config = collect_config(f)

opts = sorted(config.keys())

klib = kconfiglib.Config(sys.argv[1])
# this needs to be `make defconfig`
klib.load_config(".config")

ours = kconfiglib.Config(sys.argv[1])
ours.load_config(CONFIG_FILE)

def is_arch_specific(sym):
    return sym.get_def_locations()[0][0].startswith("arch")

arch = []
generic = []
for o in opts:
    # our hyperv patch stuff
    if o in ("AF_KCM", "HYPERV_SOCK", "VIRTIO_VSOCKETS", "VIRTIO_VSOCKETS_COMMON", "HYPERV_VSOCKETS"):
        generic.append(o)
        continue

    sym = klib.get_symbol(o)
    if sym is None:
        print("symbol %s unknown" % o)
        sys.exit(1)

    oursym = ours.get_symbol(o)
    if sym is None:
        print("symbol %s unknown" % o)
        sys.exit(1)

    # don't render invisble symbols
    if oursym.get_visibility() == 'n':
        continue

    # If defconfig of this symbol matches our value, we don't need to track it:
    value = config[o]
    if value == sym.get_value() and (KERNEL_PREV is None or prev.get(o, value) == value):
        continue

    if is_arch_specific(sym):
        arch.append(o)
    else:
        generic.append(o)

def render_diff(diff):
    for o in sorted(diff):
        value = config[o]
        if value == "n":
            print("# CONFIG_%s is not set" % o)
        else:
            print("CONFIG_%s=%s" % (o, value))

if KERNEL_PREV:
    for o in sorted(prev.keys()):
        if o not in arch and o not in config:
            print("dropped %s" % o)

    print("ARCH\n\n")
    for o in sorted(arch):
        if o in prev and prev[o] == config[o]:
            continue

        if config[o] == 'n':
            print("# CONFIG_%s is not set" % o)
        else:
            print("CONFIG_%s=%s" % (o, config[o]))

    print("\n\nGENRIC\n\n")
    for o in sorted(generic):
        if o == "VIRTUALIZATION":
            print "found virtualization"
        if o in prev and prev[o] == config[o]:
            continue
        if config[o] == 'n':
            print("# CONFIG_%s is not set" % o)
        else:
            print("CONFIG_%s=%s" % (o, config[o]))
    sys.exit(0)

print("ARCH\n\n")
render_diff(arch)
print("\n\nGENRIC\n\n")
render_diff(generic)
