CONFIG_BLK_DEV_NVME=m
CONFIG_DEVPTS_MULTIPLE_INSTANCES=y
CONFIG_GENEVE=y
CONFIG_HYPERV_SOCK=y
CONFIG_IPV6_TUNNEL=m
CONFIG_MEMCG_KMEM=y
# CONFIG_NET_VENDOR_SYNOPSYS is not set
CONFIG_PUBLIC_KEY_ALGO_RSA=y
# CONFIG_TIMER_STATS is not set
CONFIG_UPROBE_EVENT=y
